# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=50, verbose_name=b'Pesapal Transaction Tracking ID')),
                ('reference', models.CharField(max_length=50, verbose_name=b'Pesapal Merchant Reference')),
                ('status', models.CharField(choices=[(b'PENDING', b'Pending'), (b'COMPLETED', b'Completed'), (b'FAILED', b'Failed'), (b'INVALID', b'Invalid')], default=b'PENDING', max_length=9)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
        ),
    ]
