# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('method', models.CharField(choices=[(b'PE', b'Percentage'), (b'FI', b'Fixed')], help_text=b'Tax deduction method: fixed tax per product or percentage (in fraction) of price per product', max_length=2)),
                ('rate', models.FloatField(default=0.0)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'financial_tax',
                'verbose_name_plural': 'Taxes',
            },
        ),
    ]
