# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, help_text=b'Purchase Order number', max_length=50, null=True)),
                ('shipping_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('order_status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Processing', b'Processing'), (b'Complete', b'Complete'), (b'Cancelled', b'Cancelled')], max_length=20)),
                ('payment_status', models.CharField(choices=[(b'Pending', b'Pending'), (b'Authorized', b'Authorized'), (b'Paid', b'Paid')], max_length=2)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('receipt_code', models.CharField(blank=True, help_text=b'Random code generate for each order for secure access.', max_length=100, null=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(max_length=100)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text=b'Unit price of the product', max_digits=9)),
                ('quantity', models.IntegerField()),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=9, null=True)),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('tax_rate', models.FloatField(default=0.0)),
                ('tax_method', models.CharField(blank=True, choices=[(b'PE', b'Percentage'), (b'FI', b'Fixed')], max_length=2, null=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('code', models.CharField(choices=[(b'ON', b'Online'), (b'PO', b'Purchase Order')], max_length=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.CharField(max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'sales_payment_method',
                'verbose_name_plural': 'Payment Methods',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default=b'Pending', on_delete=django.db.models.deletion.CASCADE, to='orders.PaymentMethod'),
        ),
    ]
