# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-09 19:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='allocate_order',
            field=models.BooleanField(default=False),
        ),
    ]
