# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-09 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_allocate_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[(b'Pending', b'Pending'), (b'Authorized', b'Authorized'), (b'Paid', b'Paid')], max_length=20),
        ),
    ]
