# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-19 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('quantity', models.IntegerField(default=1, help_text=b'Purchased quantity')),
                ('short_description', models.CharField(blank=True, help_text=b'Short Description of product', max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True, help_text=b'Product is available for listing and sale')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('short_description', models.CharField(blank=True, help_text=b'Short Description of product', max_length=500, null=True)),
                ('description', models.TextField(blank=True, help_text=b'Full Description of the product', null=True)),
                ('price', models.DecimalField(decimal_places=2, help_text=b'Per unit price', max_digits=9)),
                ('quantity', models.IntegerField(blank=True, help_text=b'Stock quantity', null=True)),
                ('is_active', models.BooleanField(default=True, help_text=b'Product is available for listing and sale')),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('tax', models.ForeignKey(blank=True, help_text=b'Tax applied on this product, if tax exempt select none', null=True, on_delete=django.db.models.deletion.CASCADE, to='taxes.Tax')),
            ],
        ),
        migrations.AddField(
            model_name='customerprice',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
